// Define your endpoints here
const endPoints = {
  auth: {
    login: "/generate-token",
    signup: "/user/merchant",
    forgotPasswordOtp: "/user/forgotPassword/request-otp",
    forgotPasswordVerifyOtp: "/user/forgotPassword",
  },
  settings: {
    currency: "/currency",
    currencyList: "/currency/all",
    country: "/location/country",
    countryList: "/location/country/all",
    paymentType: "/paymentType",
    mop: "/mopType",
    getTransferMode: "/transferMode/active",
    transferMode: "/transferMode",
    addSubMerchant: "user/submerchant",
    addSubAdmin: "/user/subadmin",
    allSubMerchant: "/user/subusers/submerchant",
    allSubAdmin: "/user/subusers/subadmin",
    getPermission: "/user/permissions/",
    updatePermission: "/user/updatePermissions",
    merchantPaymentType: "/paymentType/merchant",
    merchantMopType: "/mopType/merchant",
    mapMerchant: "/resellerMapping",
    allMapMerchant: "/resellerMapping/search",
    allResellers: "/user/subusers/RESELLER",
    addReseller: "/user/reseller",
    allApiDocs: "/apidoc/GetAllDocuments",
    activeAPIDocs: "/apidoc/GetActiveDocs",
    apiDocsById: "/apidoc/findApiDocById",
    uploadApiDoc: "/apidoc/uploadApiDoc",
    isActiveDocStatus: "/apidoc/isActiveDoc",
    deleteApiDoc: "/apidoc/deleteDoc",
  },
  payin: {
    orders: "/orders",
    transaction: "/transaction",
    resellerTransaction: "/transaction/GetResellerTransactions",
    dashboardTransaction: "/dashboard/transactions",
    settlement: "/settlement",
    refundTxn:"/api/refund/transactions",
    settlementStatus: "/settlement/status/all",
    downloadTransaction: "/transaction/generateReport",
    addNotification: "/notificationsPreferences/add",
    getNotification: "/notificationsPreferences/all/",
    updatePriority: "/merchantTdrMdr/updateTdrPriority",
    settlementSummary: "/settlement/summary/",
    capturePayment: "/cybersource/capture/",
    captureBulk: "/cybersource/capture/bulk",
    refund: "/cybersource/refund/",
    fullRefund: "/api/refund/fullRefund",
    partialRefund: "/api/refund/partialRefund",
    settleAll: "/settlement/status/all?merchantId=",
    settlementBulk: "/settlement/status/bulk",
    chargeBack: "/admin/chargebacks",
    chargeBackTypes: "/admin/chargebacks/types",
  },
  payout: {
    acquirerList: "/merchantAcquirerTransferModeMapping/acquirers",
    getUserAccounts: "/account",
    loadMoney: "/account/loadMoney/history",
    addLoadMoney: "/account/loadMoney",
    getLoadMoney: "/loadMoney/search",
    beneficiary: "/beneficiaries",
    beneficiaryDownload: "",
    transaction: "/transferMoney/search",
    priority: "/merchantAcquirerTransferModeMapping/priorityAmountLimit",
    merchantTdr: "/merchantAcquirerTransferModeMapping",
    getMapping: "/merchantAcquirerTransferModeMapping/transferModes",
    minAmtLimit: "/transferAmountLimit",
    setAmountLimit: "/transferAmountLimit",
    getBeneficiary: "/beneficiaries/search",
    ipWhitelist: "/ipWhiteList",
    getMinimumAmountLimit:
      "merchantAcquirerTransferModeMapping/minimumAmountLimit",
    getTransferModeByAcquirer: "/acquirerTransferModeMapping",
    merchantTransferMode:
      "/merchantAcquirerTransferModeMapping/merchantTransferModes",
    singlePayout: "/transferMoney/singleTransfer",
    beneficiaryList: "/beneficiaries/search",
    govtTax: "/api/govtPayment/validateRef",
    notifyTax: "/api/govtPayment/notifyRef",
    electricity: "/api/utility/validateRef",
    notifyElectricity: "/api/utility/notifyRef",
    water: "/api/utility/validateRef",
    downloadTransaction: "/transferMoney/download",
    getOrderId: "/api/generateOrderId",
  },
  dashboard: {
    usersCount: "/dashboard/usersCounts",
    lineGraph: "/dashboard/lineGraph",
    refunds: "/dashboard/refundStatus",
    settlements: "/dashboard/settlementStatus",
    currentDay: "/dashboard/payinSummaryCurrentDay",
    totalTransactions: "/dashboard/payinTotalTxnDetails",
  },

  graph: "/dashboard/graph",
  piegraph: "/dashboard/pieGraph",

  users: {
    user: "/user",
    updateUser: "/user/updateDetails",
    allMerchantList: "/user/merchant/list",
    merchantList: "/user/merchant/all",
    allMerchantList: "/user/merchant/list",
    mappedCurrency: "/currency/mapping/",
    merchantListOnly: "/user/merchant/list",
    merchant: "/user/merchant",
    acquirer: "/acquirer",
    acquirerStatus: "/acquirer/status/",
    acquirerList: "/acquirer/all",
    reseller: "/user/reseller",
    resellerList: "",
    acquirerPayin: "/acquirer/updatePayin",
    acquirerTransferMode: "/acquirerTransferModeMapping",
    acquirerPayout: "/acquirer/updatePayout",
    address: "/user/address",
    business: "/user/business",
    status: "/user/status",
    verified: "/user/verifyUser",
    authStatus: "/user/authStatus",
    account: {
      details: "/accountDetails",
      accountLocked: "/lockedStatus",
      personalDetail: "/personalDetails",
      department: "/department",
      address: "/address",
      business: "/business",
      bank: "/bankDetails",
      logo: "/user/userImages",
    },
    resetPassword: "/user/resetPassword",
    setupPassword: "/user/merchant/setup-password",
  },
  document: "/user/document",
  documentFile: "/user/document/file",
  verifyDocument: "/user/document/verify/",
  rejectDocument: "/user/document/reject",
  mapping: {
    updateMerchantTdr: "/merchantTdrMdr/updateTdr",
    deleteMerchantTdr: "/merchantTdrMdr/charges/",
    all: "/acquirerMapping",
    merchantTdr: "/merchantTdrMdr",
    merchantAcquirer: "/merchantTdrMdr/acquirer/",
    priority: "/merchantTdrMdr/priority",
    minimumAmt: "/merchantTdrMdr/minimumAmountLimit",
    minAmtLimit: "/merchantAmountLimit",
    merchantTdrPaymentDetail: "/merchantTdrMdr/all",
    currency: "/currency/mapping",
    country: "/country/mapping",
    payinWebhook: "/merchant/webhook/payin",
    payoutWebhook: "/merchant/webhook/payout",
    settlementCycle: "/settlementCycle",
    deleteResellerMapping: "/resellerMapping/",
    allTranferModes: "/acquirerTransferModeMapping",
    addTransferMode: "/acquirerTransferModeMapping",
    refundLimit: "/user/merchant/",
  },
  payments: {
    orders: "/orders",
    checkoutRequest: "/v1/checkout/request",
    checkout: "v1/checkout",
  },
  orders: {
    order: "/v1/orders",
    orderById: "/orders/details",
    downloadOrder: "/orders/generateReport",
  },
  transaction: {
    transaction: "/v1/transaction",
    settlementDownload: "/settlement/generateReport",
  },
  fraudPrevention: {
    allFraudPrevention: "/fraudPrevention/allTypes",
    userAndType: "/fraudPrevention/userAndType",
    addNew: "/fraudPrevention",
    allUserAndType: "fraudPrevention/userAndType",
  },
  paymentLink: {
    paymentLink: "/paymentLink",
    getPaymentLink: "/paymentLink/search",
    downloadPaymentLink: "/paymentLink/generateReport",
    appKey: "/user/getAppAndSecretKey?userId=",
    addPaymentLinkMerchant: "/v1/newOrder",
  },
  remittance: {
    remittance: "/remittance",
  },
  surcharge: {
    surchargeDetails: "/surcharge/details",
    addSurcharge: "/surcharge",
    updateSurcharge: "/surcharge/updateSurcharge",
    updateSurchargeValue: "/surcharge/updateMopTypeCharge",
  },
  loginHistoryDetail: "/userActivity",
  logo: "/user/userImages/",
  loginLogo: "/user/userImages/loginImage/",
  downloadLoginHistory: "/userActivity/download",

  chargeBack: {
    allChargeBack: "/admin/chargebacks/search",
    chargeBackTypes: "/admin/chargebacks/types",
    acceptFightChargeBack: "/merchant/chargebacks/",
    uploadEvidence: "/admin/chargebacks/",
    updateResolution: "/admin/chargebacks/",
    updateStatus: "/admin/chargebacks/",
    getAllComments: "/admin/chargebacks/",
    getAllDocuments: "/admin/chargebacks/",
  },

  rollingReserve: {
    rollingReserve: "/rolling-reserve/config/",
    allRollingReserve: "/rolling-reserve/all",
    manualRelease: "/rolling-reserve/",
  },
};
export { endPoints };
