export const headers = [
  "REFUND ID",
  "REFUND STATUS",
  "REFUND AMOUNT",
  "ACQ CODE",
  "CURRENCY CODE",
  "COUNTRY CODE",
  "CUSTOMER NAME",
  "CUSTOMER EMAIL",
  "CUSTOMER CONTACT No.",
  "ORDER REQ. ID",
  "NET SETTLEMENT",
  "CREATED DATE",
  "REFUND HOLD REASON",
  "STATUS",
];

export const data = [
  {
    refundID: "6672877",
    transactionId: "fgt7557gg7",
    refundDate: "21/3/2025",
    refundAmount: 6789,
    currency: "INR",
    refundStatus: "Done",
    refundType: "Full",
    cardDigits: 8978,
    customerName: "John",
    customerPhone: 9876543210,
    bankName: "ICICI",
    refundSource: " Gateway balance",
    refundFee: 15,
  },
  {
    refundID: "9232877",
    transactionId: "fgt7557gg7",
    refundDate: "22/3/2025",
    refundAmount: 9789,
    currency: "USD",
    refundStatus: "Pending",
    refundType: "Partial",
    cardDigits: 1178,
    customerName: "Jacob",
    bankName: "American Ex",
    refundSource: "Merchany acoount balance",
    refundFee: 18,
  },
  {
    refundID: "2372877",
    transactionId: "fgt8757gg7",
    refundDate: "23/3/2025",
    refundAmount: 5589,
    currency: "INR",
    refundStatus: "Done",
    refundType: "Full",
    cardDigits: 4378,
    customerName: "Johnson",
    bankName: "Bank of China",
    refundSource: "Bank Account",
    refundFee: 12,
  },
];
