export const headers = [
  "Refund ID",
  "Refund Status",
  "Refund Amount",
  "Acq Code",
  "Currency Code",
  "Country Code",
  "Customer Name",
  "Customer Email",
  "Customer Contact No.",
  "Order Req. ID",
  "Net Settlement",
  "Created Date",
  "Refund Hold Reason",
  "Status",
];
